### ISSUE TITLE
Add it to code.dlang.org?

### ISSUE THREAD

**Issue by BlackEdder** [w0rp/dstruct#1]
Would you be willing to add this to code.dlang.org? This looks like a couple of very useful container implementations and putting it up on code.dlang.org would expose it to a wider group of people.

**Comment by w0rp** [comment]
Following my amazing months long turn around time for a simple thing, (I'm sorry...) I just tagged this library as it is now with an alpha-looking version number, and submitted it to code.dlang.org. It is currently waiting in a queue of packages to publish. One it's ready, I'll close this issue.

**Comment by w0rp** [comment]
http://code.dlang.org/packages/dstruct

It is now online.

**Comment by BlackEdder** [comment]
Nice :)
