### ISSUE TITLE
Unit test failed for WeakReference

### ISSUE THREAD

**Issue by Heromyth** [w0rp/dstruct#2]
Compiler: DMD 2.084
OS: Ubuntu

**Test code**
```d
unittest {
    class SomeType {
    }

    SomeType x = new SomeType();
    auto y = weak(x);
    auto z = weak(x); // comment this to fix

    assert(y !is z);
    assert(y == z);
}
```

Error message: `Program exited with code -11`

Try to fix:
1) remoe the second reference;
2) add tow or more members to class SomeType:
```d
class SomeType {
	string n1;
	string n2;
	// int[] data;
}
```

**Comment by w0rp** [comment]
It's cool that someone checked this code out here, I haven't touched it in years. Would you like to submit a pull request for fixing this?

**Comment by Heromyth** [comment]
We are porting some java code which using WeakReference, so we find this. About the error, the compiler didn't give much more details. So it's really difficult to debug to find out what happend.
Of course, we will have a try.
